### ISSUE TITLE
connect to own server

### ISSUE THREAD

**Issue by aleqx** [grinfans/Niffler#11]
Can this connect to a grin server that runs on a different machine on the internet (which I own)?

**Comment by xiaojay** [comment]
you mean connect to your own grin node? 
yes, in the next version

**Comment by aleqx** [comment]
My own grin node, yeah. I noticed that right now you are passing the node url in the command line to the subprocess

**Comment by xiaojay** [comment]
yes, right now, Niffler use the public grin node which i built.

**Comment by xiaojay** [comment]
done by v.0.4.2
