### ISSUE TITLE
Wallet command failed: LibWallet Error: Can't Deserialize slate

### ISSUE THREAD

**Issue by pro2pop** [grinfans/Niffler#29]
Hi. Sending via http from grin-wallet 2.0.0 ubuntu is stuck with err: Wallet command failed: LibWallet Error: Can't Deserialize slate
Sending via file is OK and sending from Niffler to ubuntu grin-wallet 2.0.0 via http is also OK.
command line is: grin-wallet send -m http -d https://my_hedwig_addres 1.0
THX

**Comment by xiaojay** [comment]
fix by version 0.4.1

**Comment by pro2pop** [comment]
Nice job!
