### ISSUE TITLE
An error occur when checking balance

### ISSUE THREAD

**Issue by upojzsb** [grinfans/Niffler#31]
I'm using Niffler 0.4.1 in macOS 14.14.5.
An error occur when checking balance. 
Here's the text shown in the Check Balance window.
> 20190720 16:33:25.530 ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Cannot make request: an error occurred trying to connect: Connection refused (os error 61)
> 20190720 16:33:25.531 WARN grin_wallet_controller::command - Starting wallet check... 20190720 16:33:25.531 WARN grin_wallet_controller::command - Updating all wallet outputs, please wait ...
> 20190720 16:33:25.872 WARN grin_wallet_libwallet::internal::restore - Starting wallet check.
> 20190720 16:33:47.654 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537784. (Highest index: 26911)
> 20190720 16:33:47.655 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:33:50.181 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537784. (Highest index: 63564)
> 20190720 16:33:50.181 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:12.683 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537785. (Highest index: 132649)
> 20190720 16:34:12.683 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:15.734 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537785. (Highest index: 245870)
> 20190720 16:34:15.734 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:38.051 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537785. (Highest index: 331211)
> 20190720 16:34:38.051 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:40.986 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 369860)
> 20190720 16:34:40.986 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:43.649 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 402867)
> 20190720 16:34:43.649 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:50.300 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 431502) 20190720 16:34:50.300 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:54.431 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 481098)
> 20190720 16:34:54.431 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:57.071 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 533166)
> 20190720 16:34:57.071 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:34:59.707 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 583413)
> 20190720 16:34:59.709 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:35:02.164 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 631033)
> 20190720 16:35:02.164 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:35:05.092 WARN grin_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1537788. (Highest index: 684165)
> 20190720 16:35:05.092 WARN grin_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
> 20190720 16:35:19.827 ERROR grin_wallet_impls::node_clients::http - get_outputs_by_pmmr_index: error contacting http://grin2-node2.niffler.org:3413. Error: Request error: Cannot make request: an error occurred trying to connect: Operation timed out (os error 60)
> 20190720 16:35:19.828 ERROR grin_wallet_controller::command - Wallet check failed: Restore Error 20190720 16:35:19.828 ERROR grin_wallet_controller::command - Backtrace:
> Wallet command failed: LibWallet Error: Restore Error

**Comment by xiaojay** [comment]
I think it's a networking problem from you host to Niffler's public grin node.
Maybe try it later will fix it

And in the next version, NIffler will support check with your local grin node.

**Comment by xiaojay** [comment]
Done by v0.4.2
