### ISSUE TITLE
No linux installer

### ISSUE THREAD

**Issue by Fornax96** [grinfans/Niffler#35]
The latest version 0.4.2 has no download for linux on the release page. The last version which does have a linux download is 0.3.1.

Is linux still supported? It says so in the readme.

**Comment by xiaojay** [comment]
Sorry, I have an issue in compile part of grin on linux.
when i work out this, .appimage verison will be available.

**Comment by quentinlesceller** [comment]
Do you need any help for that @xiaojay ?

**Comment by xiaojay** [comment]
linux version done :)

https://github.com/grinfans/Niffler/releases

**Comment by quentinlesceller** [comment]
I’ll update grin.mw page.
