### ISSUE TITLE
Grin node stays running after closing Niffler

### ISSUE THREAD

**Issue by DavidBurkett** [grinfans/Niffler#36]
The grin process remains running after closing Niffler. Is this intentional? It seems like a bad idea because the only way to close it is to kill the process, which seems like it could more easily result in corrupt data.

**Comment by xiaojay** [comment]
1. There's an options to select when to close the grin process. ("more" => "local node" => "settings")
2 . this commit https://github.com/grinfans/Niffler/commit/382defdc487c446b9ac697692911aa490edf85ce
fix a kill process bug.
3. the only way to kill grin node is to use "kill" command.

**Comment by xiaojay** [comment]
Hello, david, maybe g++ cloud kill grin node process, before g++ launch, if there's a grin process running by Niffler ?
