### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by leoyoung-69** [grinfans/Niffler#37]
I tried restore and createseveral  new wallets setting with same passward.
It always prompted **Wrong password"**. 
Here is the log:

> 2019-08-27  [debug] Time to select gnode.
> 2019-08-27  [debug] Use local gnode? true
> 2019-08-27  [debug] Connect method is remoteFirst
> 2019-08-27  [debug] Remote node height is 320887
> 2019-08-27  [debug] use remote grin node.
> 2019-08-27[debug] ownerAPIProcessPID: 6796
> 2019-08-27 1[error] start owner_api got stderr: Thread 'apis' panicked with message:
> "error binding to 127.0.0.1:XXXX: error creating server listener: 以一种访问权限不允许的方式做了一个访问套接字的尝试。 (os error 10013)"

Is there anything going wrong?

Thank you.

**Comment by xiaojay** [comment]
restart wallet and try to login again?

**Comment by leoyoung-69** [comment]
It remains even after restarting and creating new wallet.

**Comment by leoyoung-69** [comment]
I guess I found the reason. It is caused by starting Grin ++ at the same time. The problem disappeared when Grin ++ shut down. 

Thanks.

**Comment by catshitaf** [comment]
I have the same question with you, how can I fix it?

**Comment by catshitaf** [comment]
it always show "wrong password" although it was correct

**Comment by xiaojay** [comment]
> it always show "wrong password" although it was correct

do you installed g++ wallet? if so, restart your computer, and try again.

**Comment by leoyoung-69** [comment]
> 
> 
> it always show "wrong password" although it was correct

xiaojay is right. This may caused by the conflict between Niffler and Grin ++. You can't run both at the same time. 

By the way, you have to kill the processes of grin.exe and grin-wallet.exe when you want to start Grin ++ after turning off Niffler.
