### ISSUE TITLE
Restore wallet using local grin node if possible

### ISSUE THREAD

**Issue by xiaojay** [grinfans/Niffler#39]

**Comment by DavidBurkett** [comment]
I thought it shipped with a local node now. Does it still use the central server?

**Comment by xiaojay** [comment]
yes, when local node got synced.
when it don't fully synced, it will use remote server

**Comment by xiaojay** [comment]
https://github.com/grinfans/Niffler/commit/7d99cb072c57381bb2275d25cdc49657beb1ee78
