### ISSUE TITLE
Keep loading while sending tx

### ISSUE THREAD

**Issue by umiiii** [grinfans/Niffler#4]
Tried different version and failed.
Hedwig receiving function works.

**Comment by xiaojay** [comment]
what address do you send grin to? gate.io?

**Comment by xiaojay** [comment]
related [https://github.com/mimblewimble/grin/issues/2842](https://github.com/mimblewimble/grin/issues/2842)

**Comment by xiaojay** [comment]
fixed in v0.3.3
