### ISSUE TITLE
Wallet generation if Grin++ installed also

### ISSUE THREAD

**Issue by h3nr1no5** [grinfans/Niffler#42]
I have noticed that after installation I had to type password for my wallet even though I had not create one. The intro view allows me to only Remove the current wallet, which is maybe Grin++ wallet. This issue is only on PC with Grin++ installed on win10 other win10 PC without Grin++ installed works OK.

**Comment by DavidBurkett** [comment]
Grin++ and Niffler are based on different implementations of the protocol, and don't share any code, nor any data. You must have had a different grin wallet at some time in the past.

**Comment by xiaojay** [comment]
yes, I think david is right.
the wallet showing after installed Niffler should be the wallet you created using the official grin cli wallet in the past.

**Comment by h3nr1no5** [comment]
Thanks for the hint it was my old grin cli wallet I have forgot about since there were no funds. The wallet data was here: C:\Users\****\AppData\Local\Programs\.grin

**Comment by xiaojay** [comment]
yes, because Niffler use the official cli grin wallet as backend. 
so it cloud recognize the wallet which already exist.
