### ISSUE TITLE
none

### ISSUE THREAD

**Issue by umiiii** [grinfans/Niffler#5]
sorry

**Comment by DavidBurkett** [comment]
Wow really? Glad you apologized, but @xiaojay has worked hard on this wallet, and you could have easily ruined his reputation with a false claim like that.

**Comment by umiiii** [comment]
> Wow really? Glad you apologized, but @xiaojay has worked hard on this wallet, and you could have easily ruined his reputation with a false claim like that.

Really sorry about that because the grin full node shows 0 balance

**Comment by xiaojay** [comment]
It's a misunderstand. 
After run "grin-wallet check", the balance is right now.
