### ISSUE TITLE
Niffler is a nightmare

### ISSUE THREAD

**Issue by CKP1865** [grinfans/Niffler#57]
I am having terrible problems accessing my Niffler wallet.  I updated version to 0.5.0 ... now I can't access my wallet to withdraw GRIN. I get message that says "Failed to start Grin owner api. May be wrong password" ... I am entering the correct password.  What can I do to access my niffler wallet?  I have my seed phrase, but have no idea how to use it to restore my account. Please help.

**Comment by xiaojay** [comment]
In the login screen, there a link to "remove current wallet".
after you removed, it will have an option "recover from seeds".

however, make sure your seed is correct first

**Comment by CKP1865** [comment]
Thanks for the response. I followed your instructions … removed the current wallet and entered the 24 word seed phrase.  The seed phrase was absolutely correct. I set a new password and clicked on “Recover” …. nothing happened … I waited a number of minutes … still nothing. So near yet so far!  What happened?

Please advise.

**Comment by xiaojay** [comment]
what's your os?windows?
and nifffler version?

**Comment by CKP1865** [comment]
OS is Mac ... version is 0.5.0

**Comment by xiaojay** [comment]
try the newest version v0.5.1 maybe

**Comment by xiaojay** [comment]
do u installed other grin wallet?like grin++ or the official cmd grin-wallet?

**Comment by CKP1865** [comment]
I don’t understand the question … I installed the Niffler wallet version 0.5.0

I’m not aware of any other … I’ve never heard of grim++ or the official grin-wallet.

**Comment by xiaojay** [comment]
ok, try this newest version https://github.com/grinfans/Niffler/releases/tag/v0.5.1-preview
and restore from seeds again

**Comment by CKP1865** [comment]
Okay …. I updated to v0.5.1 …. entered the Seed Phrase …. was asked to set a new password …. which I did … clicked on the blue button “Recover” …. and nothing happens.

Why is nothing happening?  Will I ever recover my assets from this wallet?

What could possibly go wrong ….

**Comment by xiaojay** [comment]
sorry, test on my mac works well.
please send log on ~/.niffler/log to me (xiaojay@gmail.com)

**Comment by findbl0k** [comment]
Hi guys, getting the same error on windoze 10.

Looks like my local grin node is outdated. Going to try updating my local node. As a quick fix I tried switching to the remote grin node, but that failed. 

from ~/niffler/log:

`2020-05-01 14:02:37:625 [debug] Remote node height is 677112
2020-05-01 14:02:37:633 [debug] local node height is 521278
2020-05-01 14:02:37:640 [debug] local node peers count is 16
2020-05-01 14:02:37:646 [debug] local node height is too low or peers too small. use remote grin node.
2020-05-01 14:02:37:656 [debug] ownerAPIProcessPID: 1596
2020-05-01 14:02:37:734 [error] start owner_api got stderr: Thread 'apis' panicked with message:
"error binding to 127.0.0.1:3420: error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)"`

**Comment by xiaojay** [comment]
the error is port 3420 which is used by grin-wallet owner_api process  was taken before Niffler start.
check if any other program use port 3420

**Comment by ramheat** [comment]
nice wallet..thnx

**Comment by CKP1865** [comment]
It looks like my cry for help has been ignored. I sent messages to you from April 24, 2020 to April 27, 2020 and never got an answer that solved the problem. I am using a Mac OS computer and Niffler 0.5.1 …

Back in April, at your direction I removed the current wallet and entered the 24 word seed phrase.  The seed phrase was absolutely correct. I set a new password and clicked on “Recover” …. nothing happened. I followed your instructions through several evolutions and the same thing happened. Nothing! 

With Niffler version 0.5.1 there is no means to remove the current wallet, so when I go through the steps the result is the same … nothing happens when I click the Recover button after entering a new password. I see that I got a copy of a message talking about the local grin mode but I have no idea what that means. Also another message copy about the error being port 3420 (which is used by grin-wallet owner_api process was taken before Niffler start. check if any other program use port 3420). Again, I have no idea what that means. 

Please help me solve this problem so that I can have access to my assets. 

David

**Comment by xiaojay** [comment]
@CKP1865 do you start grin-wallet(i mean the official cli wallet) at the same time when start niffler?
if so, it conflict with each other.

**Comment by CKP1865** [comment]
I don’t understand the question. I think that I am only opening Niffler. Don’t have grin-wallet installed on this Mac computer.
