### ISSUE TITLE
using 0.6 windows preview, can not transfer and receive

### ISSUE THREAD

**Issue by myrual** [grinfans/Niffler#59]
Can not transfer grin to https://grin.connect.mixin.one/grin/4d03ba48e001d306 , this is my mobile app wallet deposit address. The engineer of the wallet app has told me many exchanges met problem on transfer and receive. The wallet has updated to correctly receive and send. 
Can not receive by hedwig now.

**Comment by myrual** [comment]
received 0.01 grin on the address by transaction hash 08679be130252f910019622ebdd0cb8650e446d498d44e31ff7f128f4433be4391 on GMT+8  2020-07-24 13:31:32. Is this you?

**Comment by xiaojay** [comment]
yes, i am debuging

**Comment by xiaojay** [comment]
fix https://github.com/grinfans/Niffler/commit/58b41e5dab464778932f9abb3640a75c2aec2eda
