### ISSUE TITLE
无法接收交易所的提款

### ISSUE THREAD

**Issue by ceozero** [grinfans/Niffler#6]
我在交易所提币的时候，发现无法接收到交易所的币，问了客服，都说 钱包版本不同 无法接收。
www.aex.com
gateio.news
这两个交易所的提币是收不到的。。我想知道有什么解决方法没？  我已经看到 钱包转账是可以选择版本了。。。收款  也可以设置版本？

**Comment by xiaojay** [comment]
outdated by grin 2.0.0 after hardfork
