### ISSUE TITLE
Poor Connection makes Hedwig Failed to receives GRIN?

### ISSUE THREAD

**Issue by billionism** [grinfans/Niffler#61]
Withdrew grin from kucoin to niffler using hedwig, but didn't arrives. Idk, maybe poor connection that makes hedwig offline sometimes. How to solve this? If the problem is hedwig switching offline while sending grin.

**Comment by billionism** [comment]
In this case, where are GRIN will be? Back to sending address or disappear in the transition?

**Comment by xiaojay** [comment]
grin still on kucoin, try to contract them
