### ISSUE TITLE
http监听有时候能用有时候不能用。

### ISSUE THREAD

**Issue by ceozero** [grinfans/Niffler#7]
![QQ图片20190527171933](https://user-images.githubusercontent.com/22513657/58409879-a18e6880-80a3-11e9-8830-37a87bb2a180.png)
 也无法强制开启。。本来好好的，重启一下钱包就凉了。。企业固定IP 做了3415端口转发的。

**Comment by xiaojay** [comment]
v0.3.2 版本已经解决这个问题，请更新

**Comment by ceozero** [comment]
就是才更新的，重启钱包就开启不了监听了。

**Comment by xiaojay** [comment]
@ceozero 应该修复这个bug了，你测试下。下载、覆盖重装 https://grin-fans.oss-cn-hangzhou.aliyuncs.com/Niffler-0.3.2-http.exe

**Comment by ceozero** [comment]
显然没有什么用，，你应该加一个提示 是否强制开启http 收款。 也许我的网络环境比较复杂。。公司网络出口有好几条。只有一条线有固定IP。。我用官方的钱包是可以随便接收的。但是你的钱包 如果检测不到外网IP通信，是直接不给开启的。

**Comment by xiaojay** [comment]
其实底层是开启的，即使连接不到ip。
我改下文案说明下

**Comment by xiaojay** [comment]
fixed in v0.3.3
