### ISSUE TITLE
Niffler doesn't send Grin coins

### ISSUE THREAD

**Issue by theend809** [grinfans/Niffler#71]
Node is working peer to peer, but nothing is send and it stays on unconfirmed? 
I could receive it easily, sending to Tradeorge is a problem. 
I made slatepack. At tradeogre.com paste slatepack. At tradeorge stays on pending and in Niffler on unconfirmed?
I saw 0 peers, I restarted the Grin node, but after 8 peers connected nothing happens?
What else can I do or what am I doing wrong? For me the first time sending Grin coins.

Also to send to bitforex.com via HTTP address given by Bitforex, only Niffler wallet doesn't accept the HTTP webaddress?

**Comment by xiaojay** [comment]
do you installed the lastest version of Niffler, which is v0.7.0.
go for help to support channel https://t.me/nifflerwallet

**Comment by theend809** [comment]
Yes, I have. It doesn't matter, it remains all the same. That I cannot send.
