### ISSUE TITLE
Niffler doesn't send Grin coins

### ISSUE THREAD

**Issue by theend809** [grinfans/Niffler#72]
Node is working peer to peer, but nothing is send and it stays on unconfirmed?
I could receive it easily, sending to Tradeorge is a problem.
I made slatepack. At tradeogre.com paste slatepack. At tradeorge stays on pending and in Niffler on unconfirmed?
I saw 0 peers, I restarted the Grin node, but after 8 peers connected nothing happens?
What else can I do or what am I doing wrong? For me the first time sending Grin coins.

Also to send to bitforex.com via HTTP address given by Bitforex, only Niffler wallet doesn't accept the HTTP webaddress?

Your answer so far: do you installed the lastest version of Niffler, which is v0.7.0.
go for help to support channel https://t.me/nifflerwallet

 My answer again: Yes, I have the latest version. It doesn't matter, it remains all the same. That I cannot send.

**Comment by theend809** [comment]
Don't close it down, when it is not sovled yet.

**Comment by theend809** [comment]
Please don't close ticket down, when it isn't solved yet.

**Comment by theend809** [comment]
I use Malwarebytes, maybe it is blocking the port for going out?

**Comment by xiaojay** [comment]
1. deposit tradeogre need 3 step, and at the last you need, finalize tx.
2. Niffler does have http/https send option, send --> send via http/https

**Comment by theend809** [comment]
Thanks, with your answer I could solve it. That 3 steps did it. You can close ticket now.
