### ISSUE TITLE
How to finalize my grin reception on my niffler account

### ISSUE THREAD

**Issue by jonesyjump** [grinfans/Niffler#73]
I just received grin in my niffler account , from a bittrex account. 
"Besteedbaar" 0
"Totaal" 0
"Niet bevestigd"0
"Niet gefinaliseerd" xxx
"'Vergrendeld" 0

Do I have to execute something else in order to get my grin into the "besteedbaar" mode?

**Comment by jonesyjump** [comment]
The moment I dowloaded the slateback response to my bittrex account , bittrex cancelled my withdrawal because the transgression of the two hour period. I tried again just now and everything went just fine!

**Comment by xiaojay** [comment]
https://docs.grin.mw/getting-started/wallets/
see the tutorial
